import { IVerificationType } from "../interfaces/interfaces";

export const twoFactorAuth = (qrCodeUrl: string): string => {
    const twoFactorAuthHTML = `
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                margin: 0;
                padding: 0;
                color: #333;
            }
            .container {
                max-width: 600px;
                margin: 50px auto;
                background-color: #fff;
                padding: 20px;
                border-radius: 10px;
                box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
                text-align: center;
            }
            h1 {
                color: #800080;
            }
            p {
                font-size: 16px;
                line-height: 1.5;
            }
            .qrcode {
                margin: 20px 0;
            }
            .button {
                display: inline-block;
                margin-top: 20px;
                padding: 10px 20px;
                font-size: 16px;
                color: #fff;
                background-color: #800080;
                border-radius: 5px;
                text-decoration: none;
            }
            .footer {
                margin-top: 20px;
                font-size: 12px;
                color: #777;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Activate Two-Factor Authentication (2FA)</h1>
            <p>Hello,</p>
            <p>For enhanced security, we recommend activating Two-Factor Authentication (2FA) on your account. Please scan the QR code below using your authentication app (such as Google Authenticator or Authy).</p>
            <div class="qrcode">
                <img src="${qrCodeUrl}" alt="QR Code for 2FA" width="200" height="200">
            </div>
            <p>Once you have scanned the code, enter the 6-digit code generated by the app to complete the 2FA setup.</p>
            <p>If you did not request this, please ignore this email.</p>
            <p>Thanks!</p>
            <div class="footer">
                <p>© 2024 Your Company. All rights reserved.</p>
                <p>This is an automated message, please do not reply.</p>
            </div>
        </div>
    </body>
`;

return twoFactorAuthHTML;
}

export const mailConfirm = (codeConfirm: string): string => {
    const mailConfirmHTML = `
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
                body {
                    font-family: Arial, sans-serif;
                    background-color: #f4f4f4;
                    margin: 0;
                    padding: 0;
                    color: #333;
                }
                .container {
                    max-width: 600px;
                    margin: 50px auto;
                    background-color: #fff;
                    padding: 20px;
                    border-radius: 10px;
                    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
                }
                h1 {
                    color: #800080;
                }
                p {
                    font-size: 16px;
                    line-height: 1.5;
                }
                .button {
                    display: inline-block;
                    margin-top: 20px;
                    padding: 10px 20px;
                    font-size: 16px;
                    color: #fff;
                    background-color: #800080;
                    border-radius: 5px;
                    text-decoration: none;
                }
                .footer {
                    margin-top: 20px;
                    font-size: 12px;
                    color: #777;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Welcome to our website!</h1>
                <p>Hello,</p>
                <p>Thank you for registering on our website. To complete your registration, please confirm your email by clicking the button below.:</p>
                <a href="http://localhost:3000/api/v1/acount/confirm-email?key=${codeConfirm}" class="button">Confirm Email</a>
                <p>If you did not request this email, please ignore it.</p>
                <p>Thanks!</p>
                <div class="footer">
                    <p>© 2024 Your Company. All rights reserved.</p>
                    <p>This is an automated message, please do not reply.</p>
                </div>
            </div>
        </body>
    `;

    return mailConfirmHTML;
}

export const resendMailConfirm = (codeConfirm: string): string => {
    const mailConfirmHTML = `
       <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
                body {
                    font-family: Arial, sans-serif;
                    background-color: #f4f4f4;
                    margin: 0;
                    padding: 0;
                    color: #333;
                }
                .container {
                    max-width: 600px;
                    margin: 50px auto;
                    background-color: #fff;
                    padding: 20px;
                    border-radius: 10px;
                    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
                }
                h1 {
                    color: #800080;
                }
                p {
                    font-size: 16px;
                    line-height: 1.5;
                }
                .button {
                    display: inline-block;
                    margin-top: 20px;
                    padding: 10px 20px;
                    font-size: 16px;
                    color: #fff;
                    background-color: #800080;
                    border-radius: 5px;
                    text-decoration: none;
                }
                .footer {
                    margin-top: 20px;
                    font-size: 12px;
                    color: #777;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Resending Email Confirmation</h1>
                <p>Hello,</p>
                <p>To confirm your registration, click the button below:</p>
                <a href="http://localhost:3000/api/v1/acount/confirm-email?key=${codeConfirm}" class="button">Confirm Email</a>
                <p>If you did not request this email, please ignore it.</p>
                <p>Thanks!</p>
                <div class="footer">
                    <p>© 2024 Your Company. All rights reserved.</p>
                    <p>This is an automated message, please do not reply.</p>
                </div>
            </div>
        </body>
    `;

    return mailConfirmHTML;
}

export const confirmCode6Digits = (code6Digits: string, verificationType: IVerificationType): string => {
    const code6DigitsHTML = `
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                margin: 0;
                padding: 0;
                color: #333;
            }
            .container {
                max-width: 600px;
                margin: 50px auto;
                background-color: #fff;
                padding: 20px;
                border-radius: 10px;
                box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
                text-align: center;
            }
            h1 {
                color: #800080;
            }
            p {
                font-size: 16px;
                line-height: 1.5;
            }
            .code {
                font-size: 24px;
                font-weight: bold;
                color: #800080;
                margin: 20px 0;
            }
            .footer {
                margin-top: 20px;
                font-size: 12px;
                color: #777;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Your code for ${verificationType} modification</h1>
            <p>Hello,</p>
            <p>To modify your ${verificationType} for your account, please enter the following 6-digit code in the verification field:</p>
            <div class="code">
                ${code6Digits}
            </div>
            <p>If you did not request this, please ignore this email.</p>
            <p>Thanks!</p>
            <div class="footer">
                <p>© 2024 Your Company. All rights reserved.</p>
                <p>This is an automated message, please do not reply.</p>
            </div>
        </div>
    </body>
`;

return code6DigitsHTML;
}